# fly.toml app configuration file generated for nuzantara-rag on 2025-11-04T22:20:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nuzantara-rag'
primary_region = 'sin'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  CHROMA_DB_PATH = '/data/chroma_db_FULL_deploy'
  EMBEDDING_DIMENSIONS = '1536'
  EMBEDDING_MODEL = 'text-embedding-3-small'
  EMBEDDING_PROVIDER = 'openai'
  NODE_ENV = 'production'
  PORT = '8000'

[[mounts]]
  source = 'chroma_data_complete'
  destination = '/data/chroma_db_FULL_deploy'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30000s'
    timeout = '5000s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
