global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nuzantara-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
